<?php
/**
* English file for plugin djg_i18n_generator
*
* @package wolf
* @subpackage djg_i18n_generator
*
* @generated by djg_i18n_generator WolfCMS plugin - Michał Uchnast <djgprv@gmail.com>
*
**/
return array(
/** DjgI18nGeneratorController.php */ 
'The settings have been updated.' => 'The settings have been updated.', 
/** enable.php */ 
'djg_i18n_generator - plugin settings initialized.' => 'djg_i18n_generator - plugin settings initialized.', 
'djg_i18n_generator - unable to store plugin settings!' => 'djg_i18n_generator - unable to store plugin settings!', 
/** index.php */ 
'[djg] i18n Generator' => '[djg] i18n Generator', 
/** uninstall.php */ 
'Unable to delete plugin settings.' => 'Unable to delete plugin settings.', 
/** views\documentation.php */ 
'Documentation' => 'Documentation', 
/** views\en_language.php */ 
'Basic en-message.php file generator.' => 'Basic en-message.php file generator.', 
'Plugin' => 'Plugin', 
'- chose plugin -' => '- chose plugin -', 
'Files' => 'Files', 
'Generate' => 'Generate', 
'Poll (:id) is :status now!' => 'Poll (:id) is :status now!', 
'Save file' => 'Save file', 
'Do you want to change the existing file?' => 'Do you want to change the existing file?', 
'Unspecified ajax error.' => 'Unspecified ajax error.', 
'The file was not saved.' => 'The file was not saved.', 
'The file has been saved as :name' => 'The file has been saved as :name', 
/** views\other_languages.php */ 
'Other languages generator.' => 'Other languages generator.', 
/** views\settings.php */ 
'Settings' => 'Settings', 
'Add a comments' => 'Add a comments', 
'Yes' => 'Yes', 
'No' => 'No', 
'Set Yes if you want to add commnet about the source file to message file.' => 'Set Yes if you want to add commnet about the source file to message file.', 
'Save' => 'Save', 
'You have modified this page.  If you navigate away from this page without first saving your data, the changes will be lost.' => 'You have modified this page.  If you navigate away from this page without first saving your data, the changes will be lost.', 
/** views\sidebar.php */ 
'English language' => 'English language', 
'Other languages' => 'Other languages', 
);