<?php
/**
* English file for plugin djg_i18n_generator
*
* @package wolf
* @subpackage djg_i18n_generator
*
* @generated by djg_i18n_generator WolfCMS plugin - Michał Uchnast <djgprv@gmail.com>
*
**/
return array(
/** DjgI18nGeneratorController.php */ 
'The settings have been updated.' => 'The settings have been updated.', 
/** enable.php */ 
'djg_i18n_generator - plugin settings initialized.' => 'djg_i18n_generator - plugin settings initialized.', 
'djg_i18n_generator - unable to store plugin settings!' => 'djg_i18n_generator - unable to store plugin settings!', 
/** index.php */ 
'[djg] i18n Generator' => '[djg] i18n Generator', 
/** uninstall.php */ 
'Unable to delete plugin settings.' => 'Unable to delete plugin settings.', 
/** views/documentation.php */ 
'Documentation' => 'Documentation', 
/** views/en_language.php */ 
'Basic en-message.php file generator.' => 'Basic en-message.php file generator.', 
'Plugin' => 'Plugin', 
'- chose plugin -' => '- chose plugin -', 
'Files' => 'Files', 
'Generate' => 'Generate', 
'Save file' => 'Save file', 
'Loaded in :time second(s).' => 'Loaded in :time second(s).', 
'Do you want to modify the existing file?' => 'Do you want to modify the existing file?', 
'Ajax error status:' => 'Ajax error status:', 
'The file was not saved.' => 'The file was not saved.', 
'The file has been saved as :name' => 'The file has been saved as :name', 
'Copied to clipboard' => 'Copied to clipboard', 
/** views/other_languages.php */ 
'Other languages generator.' => 'Other languages generator.', 
'Language' => 'Language', 
'Read en-message.php file' => 'Read en-message.php file', 
'Translate file' => 'Translate file', 
'Please wait' => 'Please wait', 
'Stop process' => 'Stop process', 
'Translate line error.' => 'Translate line error.', 
'It can take a few minutes.' => 'It can take a few minutes.', 
/** views/pattern_languages.php */ 
'Generate pattern file' => 'Generate pattern file', 
/** views/settings.php */ 
'Settings' => 'Settings', 
'Header' => 'Header', 
'' => '', 
'Add a comments' => 'Add a comments', 
'Yes' => 'Yes', 
'No' => 'No', 
'Array unique' => 'Array unique', 
'Line wrapping' => 'Line wrapping', 
'Save' => 'Save', 
'You have modified this page.  If you navigate away from this page without first saving your data, the changes will be lost.' => 'You have modified this page.  If you navigate away from this page without first saving your data, the changes will be lost.', 
/** views/sidebar.php */ 
'English language' => 'English language', 
'Pattern file' => 'Pattern file', 
'Other languages' => 'Other languages', 
'Dialog window' => 'Dialog window', 
);