<?php
/**
* English file for plugin djg_i18n_generator
*
* @package wolf
* @subpackage djg_i18n_generator
*
* @generated by djg_i18n_generator WolfCMS plugin - Michał Uchnast 
*
**/
return array(
/** DjgI18nGeneratorController.php */ 
'The settings have been updated.' => 'Ustawienia zostały zaktualizowane.',
/** enable.php */ 
'djg_i18n_generator - plugin settings initialized.' => 'djg_i18n_generator - ustawienia wtyczki zapisane.',
'djg_i18n_generator - unable to store plugin settings!' => 'djg_i18n_generator - ustawienia wtyczki nie zostały zapisane!',
/** index.php */ 
'[djg] i18n Generator' => '[djg] i18n Generator',
/** uninstall.php */ 
'Unable to delete plugin settings.' => 'Nie można usunąć ustawienia wtyczki.',
/** views/documentation.php */ 
'Documentation' => 'Dokumentacja',
/** views/en_language.php */ 
'Basic en-message.php file generator.' => 'Generator pliku en-message.php.',
'Plugin' => 'Wtyczka',
'- chose plugin -' => '- Wybierz wtyczkę -',
'Files' => 'Pliki',
'Generate' => 'Generuj',
'Save file' => 'Zapisz plik',
'Loaded in :time second(s).' => 'Załadowany w :time sekund.',
'Do you want to modify the existing file?' => 'Czy chcesz zmodyfikować istniejący plik?',
'Ajax error status:' => 'Błąd ajax:',
'The file was not saved.' => 'Plik nie został zapisany.',
'The file has been saved as :name' => 'Plik został zapisany jako :name',
'Copied to clipboard' => 'Skopiowano do schowka',
/** views/other_languages.php */ 
'Other languages generator.' => 'Generowanie innych języków.',
'Language' => 'Język',
'Read en-message.php file' => 'Przeczytaj plik en-message.php',
'Translate file' => 'Tłumaczenie plików',
'Please wait' => 'Proszę czekać',
'Stop process' => 'Zatrzymaj proces',
'Translate line error.' => 'Błąd tłumaczenie linii.',
/** views/pattern_languages.php */ 
'Generate pattern file' => 'Generowanie pliku wzorca',
/** views/settings.php */ 
'Settings' => 'Ustawienia',
'Header' => 'Nagłówek',
'' => '',
'Add a comments' => 'Dodawanie komentarzy',
'Yes' => 'Tak',
'No' => 'Nie',
'Array unique' => 'Linie unikalne',
'Line wrapping' => 'Zawijanie wierszy',
'Save' => 'Zapisz',
'You have modified this page.  If you navigate away from this page without first saving your data, the changes will be lost.' => 'Zmodyfikowaniu tej strony. Jeśli nawigacja z dala od tej strony bez wcześniejszego zapisywania danych, zmiany zostaną utracone.',
/** views/sidebar.php */ 
'English language' => 'Język angielski',
'Pattern file' => 'Szablon pliku',
'Other languages' => 'Inne języki:',
'Dialog window' => 'Okno dialogowe',
);