<?php
/**
* English file for plugin djg_i18n_generator
*
* @package wolf
* @subpackage djg_i18n_generator
*
* @generated by djg_i18n_generator WolfCMS plugin - Michał Uchnast 
*
**/
return array(
/** DjgI18nGeneratorController.php */ 
'The settings have been updated.' => 'Ustawienia zostały zaktualizowane.',
/** enable.php */ 
'djg_i18n_generator - plugin settings initialized.' => 'djg_i18n_generator - ustawienia wtyczki zapisane.',
'djg_i18n_generator - unable to store plugin settings!' => 'djg_i18n_generator - nie można zapisać ustawień wtyczki!',
/** index.php */ 
'[djg] i18n Generator' => '[djg] Generator i18n',
/** uninstall.php */ 
'Unable to delete plugin settings.' => 'Nie można usunąć ustawień wtyczki.',
/** views\documentation.php */ 
'Documentation' => 'Dokumentacja',
/** views\en_language.php */ 
'Basic en-message.php file generator.' => 'Generator pliku en-message.php.',
'Plugin' => 'Wtyczka',
'- chose plugin -' => '- wybierz plugin -',
'Files' => 'Pliki',
'Generate' => 'Generuj',
'Save file' => 'Zapisz plik',
'Loaded in :time second(s).' => 'Załadowano w :time sekund.',
'Do you want to modify the existing file?' => 'Czy chcesz zmodyfikować istniejący plik?',
'Ajax error status:' => 'Ajax status błędu:',
'The file was not saved.' => 'Plik nie został zapisany.',
'The file has been saved as :name' => 'Plik został zapisany jako :name',
'Copied to clipboard' => 'Skopiowane do schowka',
/** views\other_languages.php */ 
'Other languages generator.' => 'Inne języki generatora.',
'Language' => 'Język',
'Read en-message.php file' => 'Czytaj plik en-message.php',
'Translate file' => 'Tłumacz plik',
'Please wait' => 'Proszę czekać',
'Stop process' => 'Zatrzymaj',
'Translate line error.' => 'Przekłada błąd linii.',
'It can take a few minutes.' => 'To może potrwać kilka minut.',
/** views\settings.php */ 
'Settings' => 'Ustawienia',
'Header' => 'Nagłówek',
'' => '',
'Add a comments' => 'Dodaj komentarz',
'Yes' => 'Tak',
'No' => 'Nie',
'Array unique' => 'Usuń duplikaty',
'Line wrapping' => 'Łamanie wiersza',
'Save' => 'Oszczędzać',
'You have modified this page.  If you navigate away from this page without first saving your data' => 'Zmodyfikowaniu tej strony.  Jeżeli nawigacja z dala od tej strony bez wcześniejszego zapisywania danych',
/** views\sidebar.php */ 
'English language' => 'Język angielski',
'Other languages' => 'Inne języki',
'Dialog window' => 'Okno dialogowe',
);